#!/bin/bash

#Author: Roberto Bonafiglia
#

#command line: 
#	sudo ./start $1 $2 $3 $4 $5

#dependencies: strongswan 

#$1 LSI ID								(e.g., 2)
#$2 NF name								(e.g., firewall)
#$3 number_of_ports							(it is supposed to be 2 for this NF)
#$4 and $5 names of port1 and port2 respectively			(e.g., vEth0 vEth1)

if (( $EUID != 0 )) 
then
    echo "[nativeNF_example_start] This script must be executed with ROOT privileges"
    exit 0
fi

#enable ipv4 forwarding
sysctl -w net.ipv4.ip_forward=1

#debug
#set -x

br_name=$1_$2_br
namespace_name=$1_$2_ns

ifconfig $4 192.168.1.1 netmask 255.255.255.0
ifconfig $5 192.168.2.1 netmask 255.255.255.0
iptables -A FORWARD -i $4 -j ACCEPT
iptables -t nat -A POSTROUTING -o $5 -j MASQUERADE
exit 1
