#!/bin/bash

#Author: Roberto Bonafiglia
#

#command line: 
#	sudo ./start $1 $2 $3 $4 $5

#dependencies: strongswan 

#$1 LSI ID								(e.g., 2)
#$2 NF name								(e.g., firewall)
#$3 number_of_ports							(it is supposed to be 2 for this NF)
#$4 and $5 names of port1 and port2 respectively			(e.g., vEth0 vEth1)

if (( $EUID != 0 )) 
then
    echo "[nativeNF_example_start] This script must be executed with ROOT privileges"
    exit 0
fi

#enable ipv4 forwarding
sysctl -w net.ipv4.ip_forward=1

#debug
#set -x

br_name=$1_$2_br
namespace_name=$1_$2_ns

SCRIPTPATH="$1_$1_$2_tmp_$2"

bash $SCRIPTPATH/configure.sh $4 $5 $namespace_name $SCRIPTPATH

ip netns exec $namespace_name ipsec start 
echo "[nativeNF_strongswan_start] script executed"

exit 1
